// TODO: Replace with code generated by FlutterFire CLI.
// This placeholder avoids build errors during early development.

import 'package:firebase_core/firebase_core.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions? get currentPlatform => null;
}