// TODO: Replace with code generated by FlutterFire CLI.
// This placeholder avoids build errors during early development.

import 'package:firebase_core/firebase_core.dart';

// ⚠️ Sample configuration ONLY. Replace with real values generated by FlutterFire CLI.
class DefaultFirebaseOptions {
  static FirebaseOptions? get currentPlatform {
    return const FirebaseOptions(
      apiKey: 'AIza...Sample',
      appId: '1:1234567890:web:abcdef123456',
      messagingSenderId: '1234567890',
      projectId: 'doudizhu-sample',
      authDomain: 'doudizhu-sample.firebaseapp.com',
      storageBucket: 'doudizhu-sample.appspot.com',
      measurementId: 'G-XXXXXXX',
    );
  }
}